[build-system]
requires = [
    "cmake>=2.8.11,<5",
    "setuptools>=70.1",
]
build-backend = "setuptools.build_meta"

[project]
name = "pnextract"
version = "0.0.2"
license = "MIT"
description = "Pore network extraction from micro-CT images of porous media"
readme = "README.md"
classifiers = [
    "Development Status :: 5 - Production/Stable",
    "Environment :: Console",
    "Intended Audience :: Science/Research",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: C++",
    "Topic :: Scientific/Engineering :: Image Processing",
]
requires-python = ">=3.8"

[project.scripts]
pnextract = "pnextract.__main__:pnextract"
voxelImageProcess = "pnextract.__main__:voxel_image_process"

[project.urls]
Repository = "https://github.com/lmmp-puc-rio/pnextract-pypi"
Homepage = "https://github.com/ImperialCollegeLondon/pnextract"
